# Generated by Django 6.0.7 on 2026-07-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated, e.g. 'React, WebGL, Brand'.", max_length=300)),
                ('image', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True, verbose_name='Live site URL')),
                ('code_url', models.URLField(blank=True, verbose_name='Source code URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-year', '-created_at'],
            },
        ),
    ]
