# Generated by Django 6.0.7 on 2026-07-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Projects  — 2026', max_length=100)),
                ('heading', models.CharField(default='Projects', max_length=150)),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project section content',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectsection'),
        ),
    ]
