# Generated by Django 6.0.7 on 2026-07-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectsection_project_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectsection'),
        ),
    ]
