# Generated by Django 6.0.7 on 2026-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_alter_projectsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='eyebrow',
            field=models.CharField(blank=True, default='Projects - 2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='heading',
            field=models.CharField(blank=True, default='Projects', max_length=150),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='intro',
            field=models.TextField(blank=True, default='Its project section'),
        ),
    ]
