# Generated by Django 6.0.7 on 2026-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectsection_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='eyebrow',
            field=models.CharField(blank=True, default='Projects — 2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='intro',
            field=models.TextField(blank=True, default="A selection of projects I've built."),
        ),
    ]
