# Generated by Django 6.0.7 on 2026-07-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Portfolio — 2026', max_length=100)),
                ('name', models.CharField(default='Prabin.O', max_length=100)),
                ('role', models.CharField(default='Fullstack Developer & Designer', max_length=150)),
                ('tagline', models.CharField(default='I build interfaces that feel alive.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(default='View the projects', max_length=50)),
                ('secondary_cta_label', models.CharField(default='Download Cv', max_length=50)),
                ('image', models.URLField(blank=True, help_text='Portrait shown in the hero frame.')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Hero content',
            },
        ),
    ]
