# Generated by Django 6.0.7 on 2026-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='About — 2026', max_length=100)),
                ('heading', models.CharField(default='A little about me', max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('bio_secondary', models.TextField(blank=True)),
                ('status', models.CharField(default='Available for new projects', max_length=150)),
            ],
            options={
                'verbose_name': 'About content',
            },
        ),
    ]
