# Generated by Django 6.0.7 on 2026-07-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='cv',
            field=models.URLField(blank=True),
        ),
    ]
