# Generated by Django 6.0.7 on 2026-07-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_herocontent_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocontent',
            name='cv',
        ),
    ]
