# Generated by Django 6.0.7 on 2026-07-16 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Toolkit — 2026', max_length=100)),
                ('heading', models.CharField(default='Skills', max_length=150)),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Skills section content',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text="simple-icons slug, e.g. 'react', 'python', 'docker'.", max_length=50)),
                ('color', models.CharField(blank=True, default='F5F1EA', help_text="Hex color without the '#', e.g. 'F7DF1E'.", max_length=6)),
                ('level', models.CharField(choices=[('primary', 'Primary (featured tile)'), ('secondary', 'Secondary (compact chip)')], default='secondary', max_length=10)),
                ('note', models.CharField(blank=True, help_text='Shown only for primary skills.', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='skillgroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='skills.skillssection'),
        ),
    ]
